### ISSUE TITLE
HttpException wrong template

### ISSUE THREAD

**Issue by Yevhen-Molchaniuk** [nanogiants/nestjs-swagger-api-exception-decorator#23]
Template for HttpException is 
{
  statusCode: '$status',
  message: '$description',
  error: '$description',
}
but nestJS creates Excepiton like this
{
  statusCode: '$status',
  message: '$description',
  error: '$error',
}
Example: 
HTTP conflict: 
{
    "statusCode": 409,
    "message": "User already exists",
    "error": "Conflict"
}
but using this library i will find this in swagger: 
{
  "statusCode": 409,
  "message": "User already exists",
  "error": "User already exists"
}

**Comment by Yevhen-Molchaniuk** [comment]
Maybe it's possible to add decorator for exception class? like @Entity(), example: @ApiExceptionSchema({ status: '404'... })

**Comment by jsproede** [comment]
Hi @Yevhen-Molchaniuk, thank you for opening the issue. You're right: The issue here was, that the decorator did not use the response generated by the exception. This issue will be fixed in the next version :)

What exactly do you want to achieve with an additional decorator? You could also use the [`template` property](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/api#template) to override the default template behavior.

**Comment by Yevhen-Molchaniuk** [comment]
I am using additional decorator know for declare error attribute with type string ;)
export const ApiHttpException = buildTemplatedApiExceptionDecorator({
  statusCode: '$status',
  message: '$description',
  error: 'string',
});
Thank you for fast fixing, please notify me in this thread when new release will be, Thank You

**Comment by jsproede** [comment]
@Yevhen-Molchaniuk We just released a new version including the `error` property :) See [Release Notes](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/releasenotes/v1.3.0).

**Comment by Yevhen-Molchaniuk** [comment]
Thank you
